name: DEV Workflow
on:
  push:
    branches: [ "dev" ]
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hi World!"
      - name: Print goodbye
        run: echo "OK - bye!"
